### ISSUE TITLE
Use root path as resource

### ISSUE THREAD

**Issue by christophercliff** [claudiajs/claudia-api-builder#3]
When I set:

```js
api.get('/', myThing)
```

Then run `claudia update`, I get an error:

```js
{
     message: 'Resource\'s path part must be specified',
     code: 'BadRequestException',
     time: Mon Feb 22 2016 20:47:08 GMT-0600 (CST),
     requestId: 'bb2ad343-d9d7-11e5-bc97-275099d33c06',
     statusCode: 400,
     retryable: false,
     retryDelay: 71.45924023352563
 }
```

Is this deliberate in Claudia? It appears to be possible in the AWS console.

**Comment by gojko** [comment]
this doesn't work at the moment because we didn't think of it :) shouldn't be hard to add, I'll try to push it into the next release.

**Comment by gojko** [comment]
This should now be fixed by https://github.com/claudiajs/claudia/commit/126d6e315273caf4a9487bd35feba59157cc1c54 - if you update the claudia package to 1.0.4 (now on NPM), the root mapping should work. (although this issue is in the API Builder project, the actual mapping implementation is not here, but in the main claudia source)

Please try it and let me know if it does what you need.

**Comment by christophercliff** [comment]
That worked, thanks.
