### ISSUE TITLE
how to store env variables

### ISSUE THREAD

**Issue by adrai** [claudiajs/claudia-api-builder#9]
https://github.com/claudiajs/claudia-api-builder/blob/master/README.md#the-request-object

have I to update the claudia.json file to automatically save/update additional stage variables?

**Comment by gojko** [comment]
no, you should set the stage variables in AWS directly. I don't like keeping stage variables inside the project folder structure because they often contain secret access keys. 

You can set stage variables from the AWS web console (see [Set Stage Variables Using the Amazon API Gateway Console](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-set-stage-variables-aws-console.html)), or using the AWS CLI, like this:

```bash
aws apigateway create-deployment --rest-api-id API_ID \
  --stage-name production --variables accessKey=5465876375e273re
```

See the [DynamoDB CRUD example project](https://github.com/claudiajs/example-projects/tree/master/dynamodb-example) for an example of how that's used.
